### ISSUE TITLE
Kadane's algorithm

### ISSUE THREAD

**Issue by itsmdasifraza** [itsmdasifraza/algorithm-expert#3]

**Comment by Ayush0054** [comment]
hello,bro can i contribute in c++

**Comment by itsmdasifraza** [comment]
Hey @Ayush0054 ,
This is a test repository created only for completion of open source september challenge conducted by scaler. So you can't contribute here.

Happy Coding :)

**Comment by itsmdasifraza** [comment]
> hello,bro can i contribute in c++

Hey @Ayush0054 ,
This is a test repository created only for completion of open source september challenge conducted by scaler. So you can't contribute here.

Happy Coding :)

**Comment by Ayush0054** [comment]
No problem 😊
